### ISSUE TITLE
Decide what to do about GetCactus.php and GetComponents.php

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#14]

**Comment by rhaas80** [comment]
I removed `downloads/GetComponents.php` since it only provided the equivalent of an iframe for https://github.com/gridaphobe/CRL anyway in git hash [15fe2d2](https://github.com/EinsteinToolkit/cactuscode.org/commits/15fe2d2e16d212ee9a1d7b38785bd7b33d2dd074) "download: readd download section, remove GetComponents capture page" of [cactuscode.org](https://github.com/EinsteinToolkit/cactuscode.org)

That still leaves `documentaion/GetComponents.php` which does actually describe `GetComponents` in more detail than https://github.com/gridaphobe/CRL/blob/master/README.md does. Though not everything it says is likely still correct.

**Comment by rhaas80** [comment]
documenation/GetComponents.php has been converted to markdown and as of 89e4311 it actually is linked to from the documentation page.
