### ISSUE TITLE
Fix the site map

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#2]

**Comment by rhaas80** [comment]
I added a Liquid generated sitemap in git hash [c30f2d1](https://github.com/EinsteinToolkit/cactuscode.org/commits/c30f2d1e303349dd2e4e4f394386ddc4066790dc) "sitemap: rename to html" of [cactuscode.org](https://github.com/EinsteinToolkit/cactuscode.org).

Might need some more work:
* some pages do not have titltes
* might want to use last part of url (minus html or php or index.html) instead of title

**Comment by rhaas80** [comment]
The map code itself seems ok to me now (in d0ec14d) but the site itself could be structured more nicely, eg move the Cactus team members into a subdirectory of `about/team` or clear up the two pages titled "Publications".

**Comment by rhaas80** [comment]
Closing this since there now is a sitemap, though some page arrangments (eg teams) are a bit odd.
